- .gitignore
- README.md
- conf/application.properties
- conf/development.vars
- pom.xml
- scripts/clean.sh
- scripts/demo_db.sh
- scripts/lib/common.sh
- scripts/lib/drop-create-db
- scripts/lib/get-ip.sh
- scripts/lib/liquibase-update
- scripts/lib/mvn
- scripts/lib/rebuild-db
- scripts/lib/seed-db
- scripts/run.sh
- scripts/updater
- src/main/java/py/org/fundacionparaguaya/pspserver/PspServerApplication.java
- src/main/resources/db/liquibase/db-changelog-evolution.xml
- src/main/resources/db/liquibase/db-changelog.xml
- src/main/resources/orm.xml
- src/main/resources/persistence.xml
- src/test/java/py/org/fundacionparaguaya/pspserver/PspServerApplicationTests.java
This is just the basic layout of the project that includes:
- Spring 1.5.7
- Maven
- Liquibase
- Readme file with instructions on how to build the project from source code
> Project startup structure

- src/main/resources/create_database.sql
The create_database.sql is modified and all the initial schemes and
tables were added
> Change the current database initial setup

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-08-22T12:09.sql
I’ve modified the initial changeset. Afterwards, I renamed the first sql file that, in order to let it run during application startup.
> Liquibase changes for running the initial script

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-08-31T10:00.sql
The column task_tracking_ancestor was removed and the column
created_date was added
> Modification in the survey.task_tracking table

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/PersonDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/FamilyEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/PersonEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/ApplicationEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/dtos/CityDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/dtos/CountryDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/ApplicationControllerIntegrationTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyControllerIntegrationTest.java
Add Family and Application Integration Tests merged with develop.
> Add Family and Application Integration Tests

- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/ApplicationEntity.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-09-22T12:00.sql
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/ApplicationControllerIntegrationTest.java
The column 'is_direct' from the schema 'ps_network' was renamed to
'is_organization'. As well as all the methods and classes
where renamed from 'isDirect' to 'isOrganization'
> Update the is_direct column, methods and classes

- pom.xml
- src/main/java/py/org/fundacionparaguaya/pspserver/PspServerApplication.java
Generates a WAR file to test the app deployemet in Tomcat
> Generates WAR file

- src/main/java/py/org/fundacionparaguaya/pspserver/filters/SimpleCORSFilter.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/OrganizationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/ApplicationEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/dtos/CountryDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/ExceptionTranslatorAdvice.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationController.java
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyControllerIntegrationTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationControllerIntegrationTest.java
This PR includes:
- Changes organizationId to just `id` in OrganizationDTO
- Adds CORS filter so that browsers can send OPTIONS request to localhost
- Fixes organization update functionality, adds missing call to repository save
> Update and fix Organizations CRUD initial implementation

- IDE.md
- RUN.md
- pom.xml
- src/main/java/py/org/fundacionparaguaya/pspserver/PspServerApplication.java
- src/main/resources/application-default.properties
- src/main/resources/application-dev.properties
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-09-25T11:00.sql
This PR includes:
1. Update from jar packaging to WAR
2. Changes in main spring boot class, so we can run the war inside a Tomcat
3. Documentation update
4. New properties file `application-dev.properties` to be used in development
5. Documentation on how to setup the new `dev` profile from IntelliJ or Eclipse
> Make application a war file to deploy in AWS

- OAUTH.md
- pom.xml
- src/main/java/py/org/fundacionparaguaya/pspserver/common/dtos/ErrorDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/OAuth2ResourceServerConfig.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/WebConfig.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/WebSecurityConfig.java
- src/main/resources/application-default.properties
- src/main/resources/application-dev.properties
- src/main/resources/db/changelog/sql/2017-10-26T22:00.sql
- src/main/resources/drop_database.sql
> Enable access to swagger without authentication 

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/IndicatorsPriority.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/SnapshotIndicatorPriority.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/SnapshotIndicators.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SnapshotIndicatorEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SnapshotIndicatorPriorityEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/mapper/SnapshotIndicatorPriorityMapper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/repositories/SnapshotIndicatorPriorityRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/repositories/SnapshotIndicatorRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/SnapshotIndicatorPriorityService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotIndicatorPriorityServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotIndicatorPriorityController.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-12-01T11:20.sql
Includes the selection and specification of priorities according to the indicators of a snapshot.
> Priority indicators

- src/main/java/py/org/fundacionparaguaya/pspserver/common/pagination/PaginableList.java
- src/main/java/py/org/fundacionparaguaya/pspserver/common/pagination/PspPageRequest.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/OrganizationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/repositories/OrganizationRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/OrganizationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationController.java
Returns a paginable list for organizations
> Paginated list of organizations

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyMapDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyMapService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyMapServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyControllerTest.java
Improves the distribution of responsibilities of the family map
> Family snapshot

- src/main/java/py/org/fundacionparaguaya/pspserver/families/mapper/PersonMapper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyMapServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/NewSnapshot.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/Snapshot.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/SnapshotIndicators.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SnapshotEconomicEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/repositories/SnapshotEconomicRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/SnapshotService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/validation/SchemaValidator.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/validation/SurveyUISchemaValidator.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/repositories/CityRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/repositories/CountryRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotController.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2017-12-19T10:10.sql
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotControllerTest.java
- src/test/resources/snapshot.json
- src/test/resources/survey_schema_only.json
- src/test/resources/survey_ui_schema_only.json
Improves the life cycle of a survey
> Survey cycle

- src/test/resources/survey_schema_only.json
- src/test/resources/survey_ui_schema_only.json
Add corrections to survey fields and styles
> Survey corrections

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/Snapshot.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/mapper/SnapshotEconomicMapper.java
Corrects the storage of additional data in the snapshots. And include this data in the DTO.
> Snapshot data

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/PersonDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/FamilyEntity_.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/repositories/FamilyRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/specifications/FamilySpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/OrganizationEntity_.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/repositories/OrganizationRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/OrganizationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/specifications/OrganizationSpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/security/services/impl/UserDetailsServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationController.java
Filter organizations and families according to the connected user
> Users data access

- src/test/resources/survey_uk_schema_only.json
- src/test/resources/survey_uk_ui_schema_only.json
Add survey in survey_uk_schema_only.json file for UK
> Add survey json for UK

- src/test/resources/survey_uk_schema_only.json
- src/test/resources/survey_uk_ui_schema_only.json
Translate to EN countries and areaOfResidence.
> Translate to EN

- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
Adds an endpoint that returns the quantity of families by the connected user
> Returns the quantity of families

- src/main/java/py/org/fundacionparaguaya/pspserver/common/constants/ProtectedModule.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/LogRequestFilter.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/OAuth2ResourceServerConfig.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/filters/CorsFilter.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/filters/LogRequestFilter.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/models/LoggerVM.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/LogsController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotController.java
Adds filters that logs an information about the request when it resulted in a 500 error.
> Error log improvements

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/DashboardDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/OrganizationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/ApplicationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/OrganizationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/ApplicationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/dtos/ActivityDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/ApplicationController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationController.java
Adds the dashboard as attribute of application and organization
> Dashboard - Families counter

- checkstyle.xml
Removes false positives from rules that are not required for this project.
> Applies fine tuning for checkstyle rules

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SnapshotEconomicEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-01-11T14:00.sql
- src/test/resources/survey_uk_schema_only.json
- Save the personal information as an economic snapshot column
- Fix the UK json
> Bugs corrections

- src/main/resources/db/seed_data/snapshots_properties_attributes.csv
Corrects the configuration of a indicator question
> Corrections

- src/test/resources/survey_uk_ui_schema_only.json
> Fix the json for UK

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SurveyEntity.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-02-14T13:00.sql
Add created at property in survey
> Add created at property in survey

- scripts/jenkins_deploy.sh
Signed-off-by: fhermosilla <fhermosilla@hotmail.com>
💔Thank you!
> Add configuration to deploy aws demo

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-01-10T09:50.sql
- src/main/resources/db/changelog/sql/2018-01-22T11:31.sql
- src/main/resources/db/changelog/sql/2018-02-27T16:17.sql
-Restore sql 2018-01-22T11:31 to its original version
-Remove sql 2018-01-10T09:50
-Add sql 2018-02-27T16:17 to replace sql 2016-01-10T09:50
💔Thank you!
> Fix changelog

- src/main/resources/db/changelog/sql/2018-02-20T09:15.sql
> Fix constraint in ps_network.surveys_organizations

- docs/I18N.md
> Fix readme

- src/test/resources/survey_uk_ui_schema_only.json
> Format numbers in the JSON UI schema

- src/main/java/py/org/fundacionparaguaya/pspserver/families/events/PriorityCreatedEventListener.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
Fixes #150 by updating family without creating a new transaction. We create then another method that does create a new transaction `Propagation.REQUIRES_NEW` to be called in a async way.
💔Thank you!
> Fixes #150

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-03-23T11:02.sql
- src/main/resources/i18n/messages_en_GB.properties
- Delete unnecessary users, applications and organizations
- Add i18n for UK language
💔Thank you!
>  Delete unnecessary data and include i18n for UK

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/Property.java
- src/test/resources/survey_uk_schema_only.json
FPPSP-217 - Validate email format in Survey schema form
* Add enum "email" to FormatEnum in SurveySchema property for email validation
> FPPSP-217 - Validate email format in Survey schema form

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/Property.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/test/resources/survey_schema_only.json
- src/test/resources/survey_schema_only_demo.json
- src/test/resources/survey_uk_schema_only.json
Add show description of the indicator
💔Thank you!
> Add show description of the indicator

- pom.xml
- src/main/java/py/org/fundacionparaguaya/pspserver/common/constants/ProtectedModule.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/ApplicationProperties.java
- src/main/java/py/org/fundacionparaguaya/pspserver/config/OAuth2ResourceServerConfig.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/FamilyEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/dtos/ImageParser.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/FamilyController.java
- src/main/resources/application-default.properties
- src/main/resources/application-dev.properties
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-03-22T09:00.sql
A new endpoint PUT /api/v1/families/{family_id}/image is added, in order to allow the upload of an image for families. 
This adds the attribute image_url to both, FamilyEntity and FamilyDTO. So, now when families objects are queried from the clients, the URL of the image is accessible in the new attribute.
💔Thank you!
> Fppsp 234 - Upload a family image.

- src/main/resources/i18n/messages.properties
Fix messages.properties
💔Thank you!
> Fix messages properties

- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/ApplicationServiceImpl.java
Fix delete hub logo when changing hub logo, is not deleting the old logo because the directory is incorrect.
> Fix delete hub logo when changing hub logo

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
Fix null pointer on indicator description load
💔Thank you!
> Fix null pointer on indicator description load

- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/ApplicationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/specifications/UserApplicationSpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/security/services/UserService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/security/services/impl/UserServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/UserController.java
FPPSP-233 - Server-side filtering/search functionality for Users
> FPPSP-233 - Server-side search functionality for Users

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/enums/SurveyStoplightEnum.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/SnapshotService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotController.java
…urvey
New endpoint to query only indicators list from all snapshots of a  survey
💔Thank you!
> New endpoint to query only indicators list from all snapshots of a  survey

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/FamilyEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-04-13T15:30.sql
> FPPSP 275 -  Add  family-user relationship when taking a snapshot

- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/ApplicationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/ApplicationEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/repositories/ApplicationRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/ApplicationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/ApplicationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/ApplicationController.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-05-04T17:00.sql
- src/test/java/py/org/fundacionparaguaya/pspserver/web/rest/ApplicationControllerTest.java
FPPSP-172 - Remove columns is_partner and is_hub
* Remove is_partner and is_hub columns from applications table
* Modify Application Entity and DTO to support this changes
* Simplify/unify applications services
* Remove unused applications services
**\*\*\* OBS \*\*\* 
This PR will delete `is_partner`, `is_hub` columns from applications table, this may affect switching back to other branches before merged into develop.**
> FPPSP-172 - Remove columns is_partner and is_hub

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-05-08T09:30.sql
[FPPSP-285](http://jira.fundacionparaguaya.org.py/browse/FPPSP-285) - Set and validate maximum character length in Hubs/Orgs forms and tables
> FPPSP-285 - Set and validate maximum character length in Hubs/Orgs forms and tables

- src/main/java/py/org/fundacionparaguaya/pspserver/families/specifications/FamilySpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/dtos/SnapshotFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/specifications/SnapshotEconomicSpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotReportController.java
Report's endpoint was modified in order to return not only the report of
a single organization or all organization, but the reports of a list of
organizations.
💔Thank you!
> Modifies report's endpoint to accept a orgId list

- src/main/resources/db/seed_data/system_parameter.csv
> FPPSP-295 Inserts maximum_time parameter

- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/PersonDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/PersonEntity.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-05-25T10:30.sql
- src/main/resources/db/seed_data/snapshots_properties_attributes.csv
[FPPSP-312](http://jira.fundacionparaguaya.org.py/browse/FPPSP-312) - Fix retaking a survey for a family, set missing family personal information
> FPPSP-312 - Fix retaking a survey for a family, set missing family personal information

- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/SnapshotReportManager.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotReportController.java
[FPPSP-325](http://jira.fundacionparaguaya.org.py/browse/FPPSP-325) - Add Snapshots Datatables Report
* Snapshots datatable report in Reports tab
* Display same data as the CSV that is downloaded in the Stoplights Taken Report
* Filters by date range and by selectable organizations
* Support variable size paging and searchable on every column
* Colored indicators
> FPPSP-325 - Add Snapshots Datatables Report

- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/LabelDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/LabelEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/LabelEntity_.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/mapper/LabelMapper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/repositories/LabelRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/LabelService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/LabelServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/specifications/LabelSpecification.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/LabelController.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-06-04T16:30.sql
> FPPSP-310 Endpoint for labels

- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/OrganizationLabelDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/dtos/OrganizationLabelDTORequest.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/entities/OrganizationLabelEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/mapper/OrganizationLabelMapper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/repositories/OrganizationLabelRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/OrganizationLabelService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationLabelServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationLabelController.java
- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-06-06T10:00.sql
> FPPSP-311 Endpoint for organizations_labels

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/SnapshotService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotController.java
> Endpoint to get all family's snapshot

- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
Sets the 'user_id' of the snapshots to the id of the logged user
💔Thank you!
> Adds validation for newly created families

- src/main/java/py/org/fundacionparaguaya/pspserver/reports/dtos/SnapshotFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/SnapshotReportManager.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/repositories/SurveyRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/SurveyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SurveyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotReportController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SurveyController.java
> New snapshots report

- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/PersonEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/mapper/PersonMapper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/services/impl/SnapshotServiceImpl.java
- src/test/java/py/org/fundacionparaguaya/pspserver/surveys/service/SnapshotServiceTest.java
This PR adds a single unit test for `SnapshotService#addNewSnapshot`. Only the 'happy path' is verified, this can serve as a starting point to eventually refactor the method and add validations, code clean up, etc. and do such refactor without breaking anything.
💔Thank you!
> [Maintenence] snapshot unit test

- src/main/resources/db/changelog/db.changelog-evolution.xml
- src/main/resources/db/changelog/sql/2018-07-09T10:30.sql
Changsets in liquibase were added to remove the following tables that are no longer used:
- ps_families.family_socialeconomical_attribute
- ps_families.family_socialeconomical_attribute_active
- survey.survey_template
- survey.survey_indicador_template
- survey.survey_socioeconomics_template
- survey.intervention
- survey.intervention_tracking
💔Thank you!
> [Maintenence] Remove unused components

- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
New Snapshots Report updates
* Remove commas from user data, replace for semicolon (for CSV format)
> New Snapshots Report updates

- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
Temporary fix: change two report header names for UK
This is a temporay fix, a new feature to customize each survey's report headers is in development,
once the new feature is ready this change will be removed.
> Temporary fix: change two report header names for UK

- src/main/java/py/org/fundacionparaguaya/pspserver/common/utils/DateUtils.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyLocationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/dtos/FamilyOrganizationDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/entities/PersonEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyLocationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyOrganizationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/FamilyService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyLocationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyOrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/utils/FamilyHelper.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/ApplicationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/OrganizationService.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/ApplicationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/system/specifications/ActivityFeedSpecifications.java
- src/test/java/py/org/fundacionparaguaya/pspserver/families/service/FamilyLocationServiceTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/families/service/FamilyServiceTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/families/utils/FamilyHelperTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/surveys/service/SnapshotServiceTest.java
- src/test/java/py/org/fundacionparaguaya/pspserver/util/TestMockFactory.java
We added unit tests to FamilyService, then we made some code-cleanup, we split the service into new classes to better distribute responsibilities. At the end FamilyService has less dependencies to other classes.
💔Thank you!
> [Enhancement] Family service refactor and unit testing

- src/main/java/py/org/fundacionparaguaya/pspserver/security/repositories/TermCondPolRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/security/services/impl/TermCondPolServiceImpl.java
- It was returning all available Terms and Priv Pol, now it only returns
the latest pair per language as it should
💔Thank you!
> Fix on TermCondPol available Languages endpoint

- src/main/java/py/org/fundacionparaguaya/pspserver/families/repositories/FamilyRepository.java
- src/main/java/py/org/fundacionparaguaya/pspserver/families/services/impl/FamilyServiceImpl.java
Application of family filter: isActive == true when querying families by user.
💔Thank you!
> Apply family filter isActive == true in familyByUser endpoint/repository.

- pom.xml
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/dtos/SurveyDefinition.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SurveyEntity.java
- src/main/java/py/org/fundacionparaguaya/pspserver/surveys/mapper/SurveyMapper.java
Fix DTO to Entity mappings problem in surveys and drafts
> Fix DTO to Entity mappings problem

- src/main/java/py/org/fundacionparaguaya/pspserver/network/services/impl/OrganizationServiceImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/dtos/SnapshotFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/reports/services/impl/SnapshotReportManagerImpl.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/OrganizationController.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotReportController.java
Signed-off-by: Diego Torres <diego@povertystoplight.org>
💔Thank you!
> [multiple projects] Fixed bug in report's endpoint

- src/main/java/py/org/fundacionparaguaya/pspserver/reports/dtos/SnapshotFilterDTO.java
- src/main/java/py/org/fundacionparaguaya/pspserver/web/rest/SnapshotReportController.java
Signed-off-by: Diego Torres <diego@povertystoplight.org>
💔Thank you!
> [multiple projects] Fixed issues reported by code analyzer
